### ISSUE TITLE
Feature Request : Move computers to dedicated OU (Legal Hold reasons) 

### ISSUE THREAD

**Issue by red-erik** [EvotecIT/CleanupMonster#2]
Hello,
thank you for your work.
As a suggestion, it would be nice to have the option to MOVE, instead of DELETE, in a specified target OU
to comply with Legal Hold policies.
Regards,

Red.

**Comment by PrzemyslawKlys** [comment]
This is good idea and I already had it in mind. Initially i thought this would be part of disable process, but maybe I'll do it as separate one so one could do DISABLE and then wait for X number of days and then MOVE and then X number of days DELETE.

**Comment by PrzemyslawKlys** [comment]
I've added this feature in 2 ways:
- You can use DisableAndMove instead of just Disable and it will disable computer and move it as part of a single action. You also need `DisableMoveTargetOrganizationalUnit` done. If you have a single domain you can provide OU in form of DistinugishedName (aka string). If you have multiple domains within a forest you should provide Hashtable where key is domainname and value is DN for example

```powershell
@{
   'ad.evotec.xyz' = 'OU=Disabled,OU=Computers,OU=Devices,OU=Production,DC=ad,DC=evotec,DC=xyz'
   'ad.evotec.pl' = 'OU=Disabled,OU=Computers,OU=Devices,OU=Production,DC=ad,DC=evotec,DC=pl'
}
```
- I have also added complete separate action which now brings it to 3 actions (Disable, Move, Delete). All 3 have separate parameters and can execute in different time. Keep in mind that if set all 3 actions with same parameters only the last one (Delete) will be executed. The module goes first Disable, then Move, then Delete and it overwrites action it has to take. 

This feature requires some more testing tho

**Comment by red-erik** [comment]
Thank you very much. I'll start testing it now.

Regards,
Red.
